Api key
google/gps-measurement-tools pull request #34
Opened 2022-07-08 09:42 UTC by adaext

Move API key to local place and add a sample for `local.properties`.

2022-07-08 10:49 UTC, mohammedkhider requested changes
please replace "Ada" in the local.preperties.sample with "username" to avoid having your name in the code.

2022-07-08 17:13 UTC, adaext commented
> please replace "Ada" in the local.preperties.sample with "username" to avoid having your name in the code.

Ok, I've done.

2022-07-11 01:35 UTC, mohammedkhider approved these changes

2022-07-11 01:43 UTC, mohammedkhider requested changes

2022-07-11 01:43 UTC, mohammedkhider commented on GNSSLogger/local.properties.sample
> +MAPS_API_KEY=Google Maps API key
Replace Google Maps API key with GoogleMapsApiKey

2022-07-11 10:05 UTC, adaext commented on GNSSLogger/local.properties.sample
> +MAPS_API_KEY=Google Maps API key
> Replace Google Maps API key with GoogleMapsApiKey

Ok, thanks.

2022-07-11 11:16 UTC, merged